name: Cross-Platform Pipenv Lock

on:
  push:
    branches:
      - main
    paths:
      - Pipfile.lock
      - .github/workflows/pipenv-cross-platform.yaml

jobs:
# ============================================================================ #
#                                                                              #
#                              WINDOWS LOCK                                    #
#                                                                              #
# ============================================================================ #
  windows_lock:
    name: Windows Lock

    runs-on: windows-latest

    env:
      PIPENV_VENV_IN_PROJECT: true
      PIPENV_IGNORE_VIRTUALENVS: true
      PYTHONPATH: ${{ github.workspace }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Lock System Specific Dependencies
        run: pipenv lock --keep-outdated
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win-pipfile-lock
          path: Pipfile.lock



# ============================================================================ #
#                                                                              #
#                               LINUX LOCK                                     #
#                                                                              #
# ============================================================================ #
  ubuntu_lock:
    name: Ubuntu Lock

    runs-on: ubuntu-latest

    needs: [windows_lock]

    env:
      PIPENV_VENV_IN_PROJECT: true
      PIPENV_IGNORE_VIRTUALENVS: true
      PYTHONPATH: ${{ github.workspace }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: look around
        run: ls
      - name: Delete Old Lock
        run: rm Pipfile.lock
      - name: look around 2
        run: ls
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Download Windows Lock
        uses: actions/download-artifact@v2
        with:
          name: win-pipfile-lock
          path: Pipfile.lock
      - name: look around 3
        run: ls
      - name: look around 3.5
        run: cat Pipfile.lock
      - name: Lock System Specific Dependencies
        run: pipenv lock --keep-outdated
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-pipfile-lock
          path: Pipfile.lock

  commit_lock:
    name: Commit Cross Platform Lock
    needs: [windows_lock, ubuntu_lock]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Delete Old Lock
        run: rm Pipfile.lock
      - name: Download Final Lock
        uses: actions/download-artifact@v2
        with:
          name: linux-pipfile-lock
          path: Pipfile.lock
      - name: Commit
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'Pipfile.lock'

          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: Workflow Action CI

          # The email of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          # author_email: mail@example.com

          # Name of the branch to use, if different from the one that triggered the workflow
          # Default: the branch that triggered the run
          # branch: some-branch

          # The local path to the directory where your repository is located. You should use actions/checkout first to set it up
          # Default: '.'
          # cwd: './path/to/the/repo'

          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'CI: Cross-Platform Pipfile.lock'

          # The flag used on the pull strategy. Use NO-PULL to avoid the action pulling at all.
          # Default: '--no-rebase'
          # pull_strategy: 'NO-PULL or --no-rebase or --no-ff or --rebase'

          # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
          # Default: true
          # push: false

          # The arguments for the `git rm` command (see the paragraph below for more info)
          # Default: ''
          # remove: './dir/old_file.js'

          # Whether to use the --signoff option on `git commit` (only `true` and `false` are accepted)
          # Default: false
          # signoff: true

          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
          # Default: ''
          # tag: 'v1.0.0 --force'
